<?php

namespace ContainerIqx8Jg6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipReportCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ShipReportCommand' shared autowired service.
     *
     * @return \App\Command\ShipReportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ShipReportCommand.php';

        $container->privates['App\\Command\\ShipReportCommand'] = $instance = new \App\Command\ShipReportCommand();

        $instance->setName('app:ship-report');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
