<?php

namespace ContainerU8pQQvx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStarshipRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\StarshipRepository' shared autowired service.
     *
     * @return \App\Repository\StarshipRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'StarshipRepository.php';

        return $container->privates['App\\Repository\\StarshipRepository'] = new \App\Repository\StarshipRepository(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
