<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqx8Jg6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqx8Jg6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqx8Jg6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqx8Jg6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIqx8Jg6\App_KernelDevDebugContainer([
    'container.build_hash' => 'Iqx8Jg6',
    'container.build_id' => 'd484721f',
    'container.build_time' => 1723593847,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqx8Jg6');
